name: Add Label

on:
  issues:
    types: [labeled]

jobs:
  feature_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        if: ${{ contains(github.event.issue.labels.*.name, 'enhancement') && contains(github.event.issue.labels.*.name, 'bug') == false }}
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: feature/#${{ github.event.issue.number }}

  bugfix_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        if: ${{ contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, 'enhancement') == false }}
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: bugfix/#${{ github.event.issue.number }}
