name: Deploy and Run

on:
  push:
    branches:
      - feature/#48

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifactsId: ${{ steps.upload-artifacts.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v22.7.0
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Upload production artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          compression-level: 6
          retention-days: 1
          name: deploy-artifacts
          path: |
            dist/
            node_modules/
            package.json
            yarn.lock
            ecosystem.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        env:
          SERVER_PATH: ${{ vars.SERVER_PATH }}
          ARTIFACTS_ID: ${{ needs.build.outputs.artifactsId }}
          GITHUB_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          OWNER: ${{ github.repository_owner }}
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          envs: SERVER_PATH,ARTIFACTS_ID,GITHUB_TOKEN,REPO,OWNER
          script: |
            cd "$SERVER_PATH"
            echo 'curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -o "build.zip" "https://api.github.com/repos/$OWNER/$REPO/actions/artifacts/$ARTIFACTS_URL/zip"'
            curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -o "build.zip" "https://api.github.com/repos/$OWNER/$REPO/actions/artifacts/$ARTIFACTS_URL/zip"
            unzip "build.zip"
            yarn start:prod
