name: Release docs push

on:
  push:
    branches:
      - release/*

jobs:
  make-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v22.7.0
          cache: 'yarn'
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn --silent test:cov --coverageReporters=text > coverage.txt
      - name: Prepare coverage report in markdown
        uses: fingerprintjs/action-coverage-report-md@v2
        id: coverage
        with:
          textReportPath: './coverage.txt'
      - name: Write coverage report to file
        uses: joutvhu/write-file@v1
        with:
          path: './docs/coverage.md'
          contents: ${{ steps.coverage.outputs.markdownReport }}
          write_mode: overwrite
      - name: Insert document files to template
        uses: ryohidaka/action-md-insert@v1
        with:
          template_path: './docs/readme-template.md'
          src_dir: './docs'
          dest_file: 'README.md'
      - name: Commit docs commit and push
        env:
          E_MAIL: action@github.com
          USER_NAME: GitHub Action
        run: |
          git add README.md
          git config --global user.email "${{ env.E_MAIL }}"
          git config --global user.name "${{ env.USER_NAME }}"
          git commit -m 'docs: update coverage report with latest test results'
          git push
